In [2]:
import nltk

In [3]:
from nltk.corpus import twitter_samples

In [4]:
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     C:\Users\alami\AppData\Roaming\nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!


True

In [5]:
positive_tweets = twitter_samples.strings('positive_tweets.json')

In [6]:
negative_tweets = twitter_samples.strings('negative_tweets.json')

In [7]:
len(positive_tweets)

5000

In [8]:
len(negative_tweets)

5000

In [9]:
positive_tweets[:10]

['#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)',
 '@Lamb2ja Hey James! How odd :/ Please call our Contact Centre on 02392441234 and we will be able to assist you :) Many thanks!',
 '@DespiteOfficial we had a listen last night :) As You Bleed is an amazing track. When are you in Scotland?!',
 '@97sides CONGRATS :)',
 'yeaaaah yippppy!!!  my accnt verified rqst has succeed got a blue tick mark on my fb profile :) in 15 days',
 '@BhaktisBanter @PallaviRuhail This one is irresistible :)\n#FlipkartFashionFriday http://t.co/EbZ0L2VENM',
 "We don't like to keep our lovely customers waiting for long! We hope you enjoy! Happy Friday! - LWWF :) https://t.co/smyYriipxI",
 '@Impatientraider On second thought, there’s just not enough time for a DD :) But new shorts entering system. Sheep must be buying.',
 'Jgh , but we have to go to Bayan :D bye',
 'As an act of mischievousness, am calling the ETL layer of our in-house warehousing 

In [10]:
import re

In [11]:
tweet = positive_tweets[5]

In [12]:
tweet

'@BhaktisBanter @PallaviRuhail This one is irresistible :)\n#FlipkartFashionFriday http://t.co/EbZ0L2VENM'

In [13]:
tweet =  re.sub(r'(http|https)?:\/\/.*[\r\n]*', '', tweet)

In [14]:
tweet

'@BhaktisBanter @PallaviRuhail This one is irresistible :)\n#FlipkartFashionFriday '

In [15]:
tweet = re.sub(r'#', '', tweet)

In [16]:
tweet

'@BhaktisBanter @PallaviRuhail This one is irresistible :)\nFlipkartFashionFriday '

In [17]:
tweet = re.sub(r'\n', ' ', tweet)

In [18]:
tweet

'@BhaktisBanter @PallaviRuhail This one is irresistible :) FlipkartFashionFriday '

In [19]:
tweet = re.sub(r'@\w+ ', '', tweet)

In [20]:
tweet

'This one is irresistible :) FlipkartFashionFriday '

In [21]:
tweet = tweet.lower()

In [22]:
tweet

'this one is irresistible :) flipkartfashionfriday '

## tweet tokenizer

In [23]:
from nltk.tokenize import TweetTokenizer

In [24]:
tokenizer = TweetTokenizer()

In [25]:
tokens = tokenizer.tokenize(tweet)

In [26]:
tokens

['this', 'one', 'is', 'irresistible', ':)', 'flipkartfashionfriday']

In [27]:
from nltk.corpus import stopwords

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alami\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [30]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [31]:
tokens = [token for token in tokens if token not in stopwords.words('english')]

In [32]:
tokens

['one', 'irresistible', ':)', 'flipkartfashionfriday']

In [33]:
from nltk.stem import PorterStemmer

In [35]:
stemmer = PorterStemmer()

In [36]:
tokens = [stemmer.stem(token) for token in tokens]

In [37]:
tokens

['one', 'irresist', ':)', 'flipkartfashionfriday']

In [40]:
import string 
print (string.punctuation) 

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [42]:
def process_tweet(tweet, tokenizer,stemmer):
    tweet = re.sub(r'(http|https)?:\/\/.*[\r\n]*', '', tweet)
    tweet = re.sub(r'#','', tweet)
    tweet = re.sub(r'\n', ' ', tweet)
    tweet = re.sub(r'@\w+ ', '', tweet)
    tweet = tweet.lower()
    tokens = tokenizer.tokenize(tweet)
    tokens = [token for token in tokens if token not in stopwords.words('english')]
    tokens = [token for token in tokens if token not in string.punctuation]
    tokens = [stemmer.stem(token) for token in tokens]
    return tokens
    

In [47]:
process_tweet(positive_tweets[2], tokenizer, stemmer)

['listen', 'last', 'night', ':)', 'bleed', 'amaz', 'track', 'scotland']

In [48]:
import numpy as np

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
labels =  np.append(np.ones(5000), np.zeros(5000))

In [57]:
len(labels)

10000

In [58]:
labels

array([1., 1., 1., ..., 0., 0., 0.])

In [60]:
labels = np.array([labels])

In [61]:
labels

array([[1., 1., 1., ..., 0., 0., 0.]])

In [63]:
labels = labels.T

In [64]:
labels

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [65]:
tweets = positive_tweets + negative_tweets

In [66]:
len(tweets)

10000

In [67]:
tweets = np.array([tweets])

In [68]:
tweets = tweets.T

In [69]:
tweets

array([['#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)'],
       ['@Lamb2ja Hey James! How odd :/ Please call our Contact Centre on 02392441234 and we will be able to assist you :) Many thanks!'],
       ['@DespiteOfficial we had a listen last night :) As You Bleed is an amazing track. When are you in Scotland?!'],
       ...,
       ["where's all the jaebum baby pictures :(("],
       ['But but Mr Ahmad Maslan cooks too :( https://t.co/ArCiD31Zv6'],
       ['@eawoman As a Hull supporter I am expecting a misserable few weeks :-(']],
      dtype='<U152')

In [70]:
tweets.shape

(10000, 1)

In [71]:
labels.shape

(10000, 1)

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test =  train_test_split(tweets, labels, test_size=0.3)

In [74]:
X_train

array([['DCI today, now I wish I was going :-('],
       ['@Omar_Omark thanks omar :)'],
       ["Unfortunately today's performances at Pier Approach will not be going ahead due to the weather. :( http://t.co/PidhDm1ga3"],
       ...,
       ['@SarahRashadd straight 7elw :( at least mesh beyt3a2ad'],
       [':) my moods are so bipolar'],
       ["@tmhcuddly I'm so excited, we should definitely meet up :)"]],
      dtype='<U152')

In [75]:
y_train

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]])

In [76]:
y_train.shape

(7000, 1)

In [79]:
frequncies = {('happy', 1.0) : 50, ('happy', 0.0) : 10 }

In [80]:
frequncies.get(('happy', 1.0))

50

In [81]:
frequncies[('happy', 1.0)] = 65

In [82]:
frequncies.get(('happy', 1.0))

65

In [83]:
frequncies[('sad', 1.0)] = 5
frequncies[('sad', 0.0)] = 55

In [84]:
frequncies

{('happy', 1.0): 65, ('happy', 0.0): 10, ('sad', 1.0): 5, ('sad', 0.0): 55}

In [85]:
frequncies = {}

In [87]:
for tweet, label in zip(X_train, y_train):
    for token in process_tweet(tweet[0], tokenizer, stemmer):
        pair = (token, label[0])
        frequncies[pair] = frequncies.get(pair, 0) + 1

In [88]:
frequncies

{('dci', 0.0): 1,
 ('today', 0.0): 76,
 ('wish', 0.0): 68,
 ('go', 0.0): 156,
 (':-(', 0.0): 351,
 ('thank', 1.0): 453,
 ('omar', 1.0): 1,
 (':)', 1.0): 2461,
 ('unfortun', 0.0): 21,
 ("today'", 0.0): 3,
 ('perform', 0.0): 5,
 ('pier', 0.0): 1,
 ('approach', 0.0): 1,
 ('ahead', 0.0): 2,
 ('due', 0.0): 11,
 ('weather', 0.0): 24,
 (':(', 0.0): 3202,
 ('huhuu', 0.0): 1,
 ('thank', 0.0): 73,
 ('congratul', 0.0): 2,
 ('proud', 0.0): 5,
 ('guy', 0.0): 44,
 ('idea', 0.0): 6,
 ('happi', 0.0): 21,
 ('support', 0.0): 21,
 ('shake', 0.0): 1,
 ('head', 0.0): 18,
 ('repeatedli', 0.0): 1,
 ('nu-uh', 0.0): 1,
 ('jace', 0.0): 1,
 ('love', 0.0): 103,
 ('mostest', 0.0): 1,
 ('annnd', 0.0): 1,
 ('winchest', 0.0): 1,
 ('{:', 0.0): 1,
 ('hahah', 0.0): 5,
 ('dunwan', 0.0): 1,
 ('keep', 0.0): 26,
 ('also', 0.0): 11,
 ('suan', 0.0): 1,
 ('le', 0.0): 2,
 ('ba', 0.0): 3,
 ('haiz', 0.0): 1,
 ('see', 0.0): 91,
 ('everyon', 0.0): 19,
 ('otw', 0.0): 1,
 ('rn', 0.0): 11,
 ('miss', 0.0): 207,
 ('tweet', 0.0): 27,
 ('

In [90]:
frequncies.get(('😘', 0.0))

7

In [96]:
frequncies.get(('😘', 1.0))

8

In [93]:
frequncies.get(("sad", 1.0))

5

In [97]:
frequncies.get(('happi', 0.0))

21

In [101]:
X_train_features = np.zeros((7000, 3))

In [102]:
X_train_features

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
X_train_features.shape

(7000, 3)

In [109]:
def generate_features(X):
    for i in range(len(X_train)):
        pos_points = 0
        neg_points = 0
        tokens = process_tweet(X_train[i][0], tokenizer, stemmer)
        tokens = list(dict.fromkeys(tokens))
        for token in tokens:
            pos_points += frequncies.get((token, 1.0), 0)
            neg_points += frequncies.get((token, 0.0), 0)
        X_train_features[i, :] = np.array((pos_points, neg_points, 1))    

In [108]:
X_train_features

array([[2.070e+02, 6.520e+02, 1.000e+00],
       [2.915e+03, 7.400e+01, 1.000e+00],
       [1.280e+02, 3.426e+03, 1.000e+00],
       ...,
       [1.100e+01, 3.218e+03, 1.000e+00],
       [2.467e+03, 4.000e+00, 1.000e+00],
       [2.667e+03, 2.660e+02, 1.000e+00]])